services:
  web:
    build:
      context: .
      # Mac ユーザーなど、ホストとコンテナのユーザー情報を合わせたくない場合は以下不要です
      args:
        - host_user_name=${host_user_name}
        - host_group_name=${host_group_name}
        - host_uid=${host_uid}
        - host_gid=${host_gid}
    command: mix phx.server
    environment:
      DB_HOST: db
      OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4318
      OTEL_SERVICE_NAME: otel_sample
    links:
      - db
      - jaeger
    ports:
      - 4000:4000
    volumes:
      - .:/work
    working_dir: /work
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - dbdata:/var/lib/postgresql/data
  jaeger:
    image: jaegertracing/jaeger:2.13.0
    ports:
      - 16686:16686  # Jaeger UI
      - 4318:4318    # OTLP HTTP receiver
    environment:
      - SPAN_STORAGE_TYPE=badger
      - BADGER_EPHEMERAL=false
      - BADGER_DIRECTORY_VALUE=/badger/data
      - BADGER_DIRECTORY_KEY=/badger/key
    volumes:
      - jaeger-badger:/badger
    user: root
volumes:
  dbdata:
  jaeger-badger:
